<h2>Agregar Tarea </h2>

<form action="<?php echo APP_URL?>tasks/add" method="post">
    <label for="name">Nombre</label>
    <input id="name" name="name" type="text"/>
    <label for="description">Descripción</label>
    <input id="description" name="description" type="text"/>
    <label for="date">Fecha</label>
    <input id="date" type="date" name="date" value="<?php echo date("Y-m-d"); ?>"/>
    <label for="priority">Prioridad</label>
    <input type="range" name="priority" id="priority"  min="0" max="10">
    <label for="categories">Categories</label>
    <select name="category_id" id="categories">
        <?php foreach ($categories as $category):?>
            <option value="<?php echo $category->getId()?>"><?php echo $category->getName()?></option>
        <?php  endforeach?>
    </select>
    <input type="submit" value="Enviar">
</form>