
<h2>Lista de tareas</h2>


<a href="<?php echo APP_URL?>tasks/add">Agregar Tarea</a>
<table border="1">

    <tr>

        <th>ID</th>
        <th>Nombre</th>
        <th>Fecha</th>
        <th>Prioridad</th>
        <th>Status</th>
        <th>Acción</th>

    </tr>

    <?php foreach ($tasks as $task): ?>

        <tr>

            <td><?php echo $task->getId(); ?></td>
            <td><?php echo $task->getName(); ?></td>
            <td><?php echo $task->getDate("Y-m-d"); ?></td>
            <td><?php echo $task->getPriority(); ?></td>
            <td><?php echo $task->getStatus(); ?></td>
            <td><button>Editar</button> | <button>Eliminar</button></td>

        </tr>

    <?php endforeach; ?>

</table>