<?php $this->layout('layouts::structure', ['title' => $title]) ?>

<div class="container">
    <div class="row">
        <h2>Actualizar Tarea </h2>
        <div class="row">
            <form class="col s12 " action="<?php echo APP_URL ?>tasks/update/<?php echo $this->e($task->getId()) ?>"
                  method="post">
                <div class="row">
                    <div class="input-field col s12">
                        <input class="validate" id="name" name="name" type="text"
                               value="<?= $this->e($task->getName()) ?>" required/>
                        <label for="name">Nombre</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <input class="validate" id="description" name="description" type="text"
                               value="<?= $this->e($task->getDescription()) ?>" required/>
                        <label for="description">Descripción</label>

                    </div>
                </div>

                <div class="row">
                    <div class="input-field col s12">
                        <label>Fecha</label>
                        <input class="datepicker" type="text" name="date" value="<?= $this->e($task->getDate("Y-m-d")) ?>"/>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <p>Prioridad</p>
                        <p class="range-field">
                            <input type="range" name="priority" id="priority" min="0" max="10"
                                   value="<?= $this->e($task->getPriority()) ?>">
                        </p>

                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <select name="category_id">
                            <?php foreach ($categories as $category): ?>

                                <?= $category->getId() === $task->getCategoryId()? '<option value='.$task->getCategoryId().' selected>'.$category->getName(). '</option>': '<option value='.$task->getCategoryId().'>'.$category->getName(). '</option>'   ?>
                            <?php endforeach ?>

                        </select>
                        <label>Categorías</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <button class="btn waves-effect waves-light" type="submit" name="action">Guardar
                            <i class="material-icons right">save</i>
                        </button>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>

