<div class="container">
    <div class="row">
        <div class="col l6 s12">
            <h5 class="white-text">Título del footer</h5>
            <p class="grey-text text-lighten-4">Contenido del footer, Coloca lo que sea.</p>
        </div>
        <div class="col l4 offset-l2 s12">
        </div>
    </div>
</div>
<div class="footer-copyright">
    <div class="container">
        © 2018 Realizado por Steeve
        <a class="grey-text text-lighten-4 right" href="http://steeve.me">Visítame a steeve.me</a>
    </div>
</div>

