
<div class="navbar-fixed">
    <nav>
        <div class="nav-wrapper container">
            <a href="<?php echo APP_URL?>" class="brand-logo">Tareas</a>
            <a href="<?php echo APP_URL?>" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">
                <li><a href="<?php echo APP_URL?>tasks">Tareas</a></li>
                <li><a href="<?php echo APP_URL?>categories">Categorías</a></li>

            </ul>
        </div>
    </nav>
</div>


<ul class="sidenav" id="mobile-demo">
    <li><a href="<?php echo APP_URL?>tasks">Tareas</a></li>
    <li><a href="<?php echo APP_URL?>categories">Categorías</a></li>

</ul>

